# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'TennisApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TennisApp
    pod 'Firebase/Core'
    pod 'Fabric', '~> 1.7.2'
    pod 'Crashlytics', '~> 3.9.3'



end

target 'TennisApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TennisApp-tvOS

  target 'TennisApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
